site_name: Titan Shifter Megapack Documentation
nav:
    - Home: index.md
    - Titans:
        - Titans: titans.md
        - Attack Titan: titans/attack.md

theme:
    name: dracula
    palette:
        accent: indigo
        
extra_css: [extra.css]

markdown_extensions:
    - toc:
        separator: "_"
    - admonition
