site_name: Titan Shifter Megapack Documentation
nav:
    - Home: index.md
    - Titans:
        - All Titans: titans.md
        - Attack Titan: titans/attack.md

theme:
    name: dracula
    icon: images/tsmpicon.png
    favicon: images/tsmpicon.png
        
extra_css: [extra.css]

markdown_extensions:
    - toc:
        separator: "_"
    - admonition
