site_name: Titan Shifter Megapack Documentation
nav:
    - Home: index.md
    - FAQ: misc/faq.md
    - Configuration: misc/config.md
    - Titans:
        - All Titans: titans.md

        - Attack Titan: titans/attack.md
        - Female Titan: titans/female.md
        - Armored Titan: titans/armor.md
        - Beast Titan: titans/beast.md
        - Warhammer Titan: titans/warhammer.md
        - Jaw Titan: titans/jaw.md
        - Cart Titan: titans/cart.md
        - Colossal Titan: titans/colossal.md
        - Founding Titan: titans/founding.md
    - Misc:
        - Pure Titans: misc/pure_titans.md
        - Titan Stealing: misc/titan_stealing.md
        - Injections: misc/injections.md
        - Royal Blood: misc/royal_blood.md
        - Cart Mounts: misc/cart_mounts.md

theme:
    name: dracula
    icon: images/tsmpicon.png
    favicon: images/tsmpicon.png
        
extra_css: [extra.css]

markdown_extensions:
    - toc:
        separator: "_"
    - admonition
